DIRS:
  DATA: ""
  OUTPUT: ""
MODEL:
  ARCH: "VAE"
  ADVERSARY: False
  ADDED_CONSTR: False
  MODE: "train"
  DEPTH: 64
DATA:
  DATASET: "svhn"
  BATCH_SIZE: 1024
  COLORS: 3
SOLVER:
  SEED: 1
CLUSTER:
  N_RUNS: 1000
