DIRS:
  DATA: ""
  OUTPUT: ""
MODEL:
  ARCH: "Baseline"
  ADVERSARY: True
  ADDED_CONSTR: True
  MODE: "train"
  DEPTH: 64
DATA:
  DATASET: "svhn"
  BATCH_SIZE: 1024
  COLORS: 3
SOLVER:
  SEED: 1
CLUSTER:
  N_RUNS: 1000
